baseURL = "/"
languageCode = "en-us"
title = "Shooonya"
theme = "ink-free"
paginate = 10

copyright = "© Jayakrishnan Nair"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[author]
    name = "Example"
    github = "funkydan2"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Technology | Photography | Books"

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false

	# Enable a table of contents
	toc = true

	# Max tags
  	maxTags = 7

  # Define words per minute to approximate reading time
  wpm = 250

	# Stupid footers :)
	footers = [ 
	
	]

	# Github base url
  	github = "https://github.com/chollinger93/ink-free"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jayakrishnannair/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
