baseURL = ""
languageCode = "en-us"
title = "Shooonya"
theme = "hugo-kiera"
paginate = 25
copyright = "Copyright &copy; 2020 - Jayakrishnan Nair"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = ""
googleAnalytics = "UA-53453810-1"

[permalinks]
  posts = "/:year/:month/:title/"

[author]
  name = "Jayakrishnan Nair"
  github = "jayakrishnannair"
  linkedin = "jayakrishnanbnair"
  twitter = "jnair_dev"

[params]
   author = "Jayakrishnan Nair"
   description = "Technology. Books. Photography"
   tagline = "Technology; Books; Photography"
   homepageLength=10
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
  identifier = "bookshelf"
  name = "Bookshelf"
  url = "/bookshelf/"
  weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 5


