baseURL = 'https://shooonya.org/'
languageCode = 'en-us'
title = 'Shooonya'
theme = 'PaperMod'

[params]
  description = "Technology | Books | Photography"
  subtitle = "Technology | Books | Photography"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
